### ISSUE TITLE
Can routes without controllers be translated?

### ISSUE THREAD

**Issue by noAlvaro** [francesc/rails-translate-routes#36]
Consider this configuration:

```
#config/routes.rb
resources :simple
resources :simple_alias, :path => '/simple-alias', :controller => :simple
```

... plus this one:

```
#config/locales/routes.yml
pt:
  routes:
    simple: simples
    simple_alias: altalho
```

This does make `/simple`, `/simples` and `/simple-alias` work. But `/atalho` won't work with that.
The only difference I can read, is that the first resource has a real dedicated controller for itself, the second doesn't.

Could this be a bug?

**Comment by noAlvaro** [comment]
Just realised that the use of `:path` parameter conflicts with the gem.

This is a bit ugly, but works:

```
#config/routes.rb
resources :simple
resources 'simple-alias', :controller => :simple, :as => :simple_alias

#config/locales/routes.yml
pt:
  routes:
    simple: simples
    simple-alias: altalho
```

Done!
